import "./globals.css";
// import { Inter } from "next/font/google";
import LoginBtn from "./LoginBtn";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <body>
      <div className="navbar">
        <Link href="/" className="logo">
          Nextforum
        </Link>
        <Link href="/list">List</Link>
        <LoginBtn></LoginBtn>
      </div>
      {children}
    </body>
  );
}
